
Представим, что нам нужно добавить на страницу несколько блоков с определёнными элементами по тегу и атрибуту
В результате выполнения этого кода у нас будет один элемент без `id`

```JS
'use strict';

// Содержит будущие элементы
const data = [
    {
        id: 'box',
        tag: 'div'
    },
    {
        id: '',
        tag: 'nav'
    },
    {
        id: 'circle',
        tag: 'span'
    }
]

// Выводит эти элементы на страницу
data.forEach(blockObj => {
	// Создаст элемент с определённым тегом
    const block = document.createElement(blockObj.tag);
    // Добавит ему определённый атрибут
    block.setAttribute('id', blockObj.id);
    // Добавит элемент на страницу
    document.body.append(block);
})
```

![](_png/e9d2178f49a1e411cc5c49f024019685.png)

Однако если мы воспользуемся оператором `throw`, то мы сможем предотвратить ошибку. Этот оператор выдаёт в консоль какое-то сообщение (строку `'string'` или созданную нами ошибку `new Error()`) и останавливает выполнение дальнейшего кода
По итогу мы получим только один элемент

```JS
data.forEach((blockObj, i) => {
    const block = document.createElement(blockObj.tag);

    if (!blockObj.id) throw new Error(`Под индексом ${i} нет данных об id`); // !

    block.setAttribute('id', blockObj.id);
    document.body.append(block);
})
```

![](_png/fc1a0f6f38ae93fd875dffbf6cbf7710.png)
![](_png/0a4ff63d2b033fa62ece9bfbb7196baa.png)

Так же есть `SyntaxError`, `TypeError`, `ReferenceError` и другие ошибки, которые можно выделить под определённые предполагаемые ситуации

```JS
const err = new ReferenceError('Ref Err');
console.log(err.name, err.message, err.stack);
```

И вот пример самих сущностей, которые мы получаем при ошибке

```JS
try {
    data.forEach((blockObj, i) => {
        const block = document.createElement(blockObj.tag);
        if (!blockObj.id) throw new SyntaxError(`Под индексом ${i} нет данных об id`);
        block.setAttribute('id', blockObj.id);
        document.body.append(block);
    })
} catch (e) {
    console.error(e.name);
    console.log(e.message);
    console.log(e.stack);
}
```

![](_png/9b9b465955681281e759d4c82dc55775.png)

Так же мы можем дописать логику для непредвиденных ошибок, которые выходят за рамки того, что можно предугадать. Для этого через условие можно прописать в блоке `catch`, какую ошибку мы ожидаем получить, а какая ошибка уже говорит о критических недоработках кода

```JS
'use strict';

const data = [
    {
        id: 'box',
        tag: 'div'
    },
    {
        id: 'had', // нормально
        tag: 'nav'
    },
    {
        id: 'circle',
        tag: '' // другая ошибка
    }
]

try {
    data.forEach((blockObj, i) => {
        const block = document.createElement(blockObj.tag);
        if (!blockObj.id) throw new SyntaxError(`Под индексом ${i} нет данных об id`);
        block.setAttribute('id', blockObj.id);
        document.body.append(block);
    })
} catch (e) {
    if (e.name === 'SyntaxError') { // если моя ошибка
        console.error(e.message); // То вывести сообщение ошибки
    } else throw e; // если ошибка не моя (непредвиденная), то пропустить ошибку
}
```

![](_png/bcd3d9febfff59658a2dc5d31bea4e86.png)